name: Check Challenge Indexes

on:
  pull_request:
    paths:
      - 'challenges/**'

jobs:
  check-index:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Check for duplicate indexes
      run: |
        python - << 'EOF'
        import os
        import collections

        challenges_dir = "challenges"

        questions = collections.defaultdict(list)
        for folder in os.listdir(challenges_dir):
            folder_path = os.path.join(challenges_dir, folder)
            for question in os.listdir(folder_path):
                idx = question.split("_")[0]
                questions[idx].append(question)
                if len(questions[idx]) > 1:
                    print(f"PR duplicated found: \n {questions[idx]}.")
                    exit(1)
        print("✅ All indexes are unique.")
        EOF